### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Neal08** [asherAgs/amzSear#10]
Hello,

I have installed amzsear but when i try to search something i get the following error:

Desktop# amzsear 'Harry Potter'
Traceback (most recent call last):
  File "/usr/local/bin/amzsear", line 7, in <module>
    from amzsear.cli.cli import run
  File "/usr/local/lib/python2.7/dist-packages/amzsear/__init__.py", line 4, in <module>
    from .amzsear.core.AmzSear import AmzSear
ImportError: No module named amzsear.core.AmzSear

Can you help me to solve this issue please?

Thank you.
Neal

**Comment by lucas-becirspahic** [comment]
Hello, I also have this problem. On the other hand, the previous version (2.0.0) of amzsear did not have this problem.

To use the previous version you can do:

`pip uninstall amzsear`
`pip install amzsear==2.0.0.0 --user`

**Comment by andrecgmachado13** [comment]
Hi, 
I have the same problem. And I'tried to uninstall and reinstal v 2.0 and does not work. 


My enviroment:
$ pip list
Package          Version   
---------------- ----------
amzsear          2.0.0     
awscli           1.14.32   
blockchain       1.4.0     

$ amzsear 'Harry'
Traceback (most recent call last):
  File "/Users/USER/Library/Python/2.7/bin/amzsear", line 7, in <module>
    from amzsear.cli.cli import run
ImportError: No module named amzsear.cli.cli

I tried:
pip uninstall amzsear
pip install amzsear==2.0.0.0 --user

and does not fix! 

Can someone help me? 

Thanks a lot!

**Comment by kailuo93** [comment]
I have forgotten most of the detail, 
After I update my python to 3.7, it seems working.
You can try, but I can't guarantee this method will work.
