### ISSUE TITLE
cssselector dependency

### ISSUE THREAD

**Issue by cagnulein** [asherAgs/amzSear#19]
I think you have to add cssselector dependency

```
Traceback (most recent call last):
  File "/usr/local/bin/amzsear", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/amzsear/cli/cli.py", line 22, in run
    out = AmzSear(**amz_args)
  File "/usr/local/lib/python3.6/dist-packages/amzsear/core/AmzSear.py", line 84, in __init__
    products = html_el.cssselect('li[id*="result_"]')
  File "/usr/local/lib/python3.6/dist-packages/lxml/html/__init__.py", line 431, in cssselect
    from lxml.cssselect import CSSSelector
  File "/usr/local/lib/python3.6/dist-packages/lxml/cssselect.py", line 16, in <module>
    'cssselect does not seem to be installed. '

```

**Comment by bgoodr** [comment]
I confirmed this. Probably have to deal with it using conda, but not sure yet.  Encountered similar issue with lxml not being present in my configuration too, which also is dealt with using conda.

**Comment by bgoodr** [comment]
The installation steps I used were conda-based, and pip-based via:

    conda install cssselect
    conda install lxml
    pip install AmzSear

but that did not help much because I see the same problem in https://github.com/asherAgs/amzSear/issues/17 and thus am now speculating we have "abandonment issues" in https://github.com/asherAgs/amzSear/issues/21 

Hopefully the owners of this package will give us some info on the status of it.
