### ISSUE TITLE
No results returned

### ISSUE THREAD

**Issue by vasi26ro** [asherAgs/amzSear#27]
I tried your module today in order to get some data from amazon about some products but any way I tried is not returning anything.

``` bash
❯ amzsear "blundstone" -r DE
  Title  Prices  Rating 

❯ amzsear "blundstone" -r UK
  Title  Prices  Rating 

❯ amzsear "blundstone" -r UK -i 1
Traceback (most recent call last):
  File "/home/dog/Documents/projects/rotar/amazon-api/amazon-venv/bin/amzsear", line 11, in <module>
    load_entry_point('amzsear==2.0.1', 'console_scripts', 'amzsear')()
  File "/home/dog/Documents/projects/rotar/amazon-api/amazon-venv/lib/python3.8/site-packages/amzsear/cli/cli.py", line 26, in run
    prod = out[args['item']]
  File "/home/dog/Documents/projects/rotar/amazon-api/amazon-venv/lib/python3.8/site-packages/amzsear/core/AmzSear.py", line 113, in __getitem__
    return self.get(key, default=None, raise_error=True)
  File "/home/dog/Documents/projects/rotar/amazon-api/amazon-venv/lib/python3.8/site-packages/amzsear/core/AmzSear.py", line 144, in get
    raise KeyError('The key %s is not a know index' % (repr(key)) ) 
KeyError: "The key '1' is not a know index"

```

Is there any fix, or I am doing something wrong?

**Comment by TonyStew** [comment]
Same issue here.  Did you ever fix it or is this repo just too out of date?

**Comment by Kugeleis** [comment]
Apparently this is not maintained. Problem persists.

**Comment by ctosaincube** [comment]
encountering the same issue
