### ISSUE TITLE
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root']

### ISSUE THREAD

**Issue by devilmind81** [asherAgs/amzSear#30]
Hi,
I'm trying to install it on raspberry but I'm obtaining the following issue when run `pip install amzsear`
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 280, in run
    wheel_cache = WheelCache(options.cache_dir, options.format_control)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cache.py", line 293, in __init__
    self._ephem_cache = EphemWheelCache(format_control)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cache.py", line 262, in __init__
    globally_managed=True,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py", line 141, in __init__
    path = self._create(kind)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/utils/temp_dir.py", line 189, in _create
    tempfile.mkdtemp(prefix="pip-{}-".format(kind))
  File "/usr/lib/python2.7/tempfile.py", line 331, in mkdtemp
    dir = gettempdir()
  File "/usr/lib/python2.7/tempfile.py", line 275, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
    ("No usable temporary directory found in %s" % dirlist))
IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/root']
```
Can you help me?

**Comment by devilmind81** [comment]
a full-upgrade fixed the issue
